version: '2'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./output:/usr/share/nginx/html 
      - ./nginx-cors.conf:/etc/nginx/conf.d/nginx-cors.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  tiles:
    build: .
    ports:
    - "8081:80"
    volumes:
    - ./data/LAA/1907050201:/data 
    image: "klokantech/iiifserver-iipimage-jpeg2000"
